version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: cinema-booking-postgres-container
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
